"""initial_tables

Revision ID: 5fb1c261fa23
Revises: 
Create Date: 2026-06-09 19:21:11.481894
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5fb1c261fa23'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feishu_id', sa.String(length=64), nullable=True, comment='飞书部门ID'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='部门名称'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父部门ID'),
    sa.Column('path', sa.String(length=512), nullable=True, comment='部门路径(如: /总部/技术部/后端组)'),
    sa.Column('status', sa.Enum('active', 'inactive', name='department_status'), nullable=True, comment='状态'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_feishu_id'), 'departments', ['feishu_id'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False, comment='角色名称'),
    sa.Column('description', sa.String(length=256), nullable=True, comment='角色描述'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feishu_id', sa.String(length=64), nullable=True, comment='飞书用户ID'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='用户名'),
    sa.Column('email', sa.String(length=256), nullable=True, comment='邮箱'),
    sa.Column('avatar', sa.String(length=512), nullable=True, comment='头像URL'),
    sa.Column('department_id', sa.Integer(), nullable=True, comment='部门ID'),
    sa.Column('status', sa.Enum('active', 'inactive', name='user_status'), nullable=True, comment='状态'),
    sa.Column('is_admin', sa.Boolean(), nullable=True, comment='是否管理员'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_feishu_id'), 'users', ['feishu_id'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='操作人ID'),
    sa.Column('action', sa.String(length=64), nullable=False, comment='操作类型(create/update/delete/approve/reject/login)'),
    sa.Column('target_type', sa.String(length=64), nullable=True, comment='目标类型(user/role/skill/tool/permission_request)'),
    sa.Column('target_id', sa.Integer(), nullable=True, comment='目标ID'),
    sa.Column('detail', sa.JSON(), nullable=True, comment='操作详情(JSON)'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP地址'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permission_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='申请人ID'),
    sa.Column('type', sa.Enum('skill', 'tool', name='request_type'), nullable=False, comment='申请类型'),
    sa.Column('target_id', sa.Integer(), nullable=False, comment='目标ID(skill或tool的ID)'),
    sa.Column('reason', sa.Text(), nullable=True, comment='申请理由'),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'cancelled', name='request_status'), nullable=True, comment='申请状态'),
    sa.Column('reviewed_by', sa.Integer(), nullable=True, comment='审批人ID'),
    sa.Column('review_comment', sa.Text(), nullable=True, comment='审批备注'),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True, comment='审批时间'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False, comment='技能名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='技能描述'),
    sa.Column('config', sa.JSON(), nullable=True, comment='技能配置(JSON)'),
    sa.Column('status', sa.Enum('active', 'inactive', name='skill_status'), nullable=True, comment='状态'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tools',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=True, comment='所属技能ID'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='工具名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='工具描述'),
    sa.Column('parameters', sa.JSON(), nullable=True, comment='工具参数定义(JSON)'),
    sa.Column('endpoint', sa.String(length=512), nullable=True, comment='工具调用端点'),
    sa.Column('method', sa.String(length=10), nullable=True, comment='调用方法(GET/POST)'),
    sa.Column('status', sa.Enum('active', 'inactive', name='tool_status'), nullable=True, comment='状态'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role_tools',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_tools')
    op.drop_table('tools')
    op.drop_table('role_skills')
    op.drop_table('user_roles')
    op.drop_table('skills')
    op.drop_table('permission_requests')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_feishu_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_index(op.f('ix_departments_feishu_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
